version: "3.9"

services:
  service-discovery:
    build: service-discovery
    image: service-discovery
    container_name: service-discovery
    ports:
      - "8761:8761"

  gateway:
    build: gateway
    image: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery

  config-server:
    build: config-server
    image: config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - service-discovery

  user-service:
    build: user-service
    image: user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - db
      - config-server
      - gateway

  notification-service:
    build: notification-service
    image: notification-service
    container_name: notification-service
    ports:
      - "8082:8082"
    depends_on:
      - user-service

  db:
    image: postgres:16-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=users

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER