spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/users/**
        - id: notification-service
          uri: http://notification-service:8082
          predicates:
            - Path=/emails/**

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka